HOSTNAME = "plamen-arch"
CPUS = 2
MEMORY = 1024
INTERFACE = ""
NODES = 1
DOMAIN = ""

Vagrant.configure("2") do |config|

    config.vm.box = "archlinux/archlinux"
    config.vm.synced_folder '.', '/vagrant', disabled: true

    (1..NODES).each do |i|

        n = i if NODES > 1

        config.vm.define "#{HOSTNAME}#{n}" do |node|

            if DOMAIN.nil? || DOMAIN.empty?
                node.vm.hostname = "#{HOSTNAME}#{n}"
            else
                node.vm.hostname = "#{HOSTNAME}#{n}.#{DOMAIN}"
            end

            if INTERFACE.to_s.empty?
                node.vm.network :private_network, ip: "10.19.0.#{i + 1}"
            else
                node.vm.network "public_network", bridge: "#{INTERFACE}"
            end

            node.vm.provider "virtualbox" do |vb|
                vb.name = node.vm.hostname
            end
        end
    end

    # Provider: virtualbox
    config.vm.provider "virtualbox" do |vb|

        vb.gui = false

        # General
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]

        # System
        vb.memory = MEMORY
        vb.customize ["modifyvm", :id, "--boot1", "disk"]
        vb.customize ["modifyvm", :id, "--boot2", "dvd"]
        vb.customize ["modifyvm", :id, "--boot3", "none"]
        vb.customize ["modifyvm", :id, "--boot4", "none"]
        vb.customize ["modifyvm", :id, "--chipset", "ich9"]
        vb.customize ["modifyvm", :id, "--mouse", "ps2"]
        vb.customize ["modifyvm", :id, "--apic", "on"]
        vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
        vb.cpus = CPUS
        vb.customize ["modifyvm", :id, "--pae", "on"]
        vb.customize ["modifyvm", :id, "--paravirtprovider", "default"]
        vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
        vb.customize ["modifyvm", :id, "--vtxvpid", "on"]
        vb.customize ["modifyvm", :id, "--vtxux", "on"]

        # Display
        vb.customize ["modifyvm", :id, "--vram", "16"]
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]

        # Storage
        vb.customize ["storagectl", :id, "--name", "IDE Controller", "--controller", "ICH6", "--hostiocache", "on"]
        vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", "0", "--device", "0", "--type", "hdd", "--nonrotational", "on"]

        # Audio
        vb.customize ["modifyvm", :id, "--audio", "none"]

        # Network
        vb.customize ["modifyvm", :id, "--nictype1", "82540EM"]

        # USB
        vb.customize ["modifyvm", :id, "--usb", "on", "--usbehci", "on"]
    end
end
# vim: ft=ruby:ai:ts=4:sw=4:sts=4
